server:
  port: 4000
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_ZONE}
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
logging:
  level:
    root: INFO