server:
  port: 0
spring:
  application:
    name: frequency-api
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_ZONE}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    instance-id: frequency-api:${random.uuid}
logging:
  level:
    root: INFO