server:
  port: 0
spring:
  application:
    name: frequency-config
  cloud:
    config:
      enabled: false
      server:
        native:
          search-locations: classpath:/service
  profiles:
     active: native
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_ZONE}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
logging:
  level:
    root: INFO