server:
  port: 0
spring:
  application:
    name: frequency-config
  cloud:
    config:
      enabled: false
      server:
        native:
          search-locations: classpath:/service
  profiles:
    active: native
logging:
  level:
    root: INFO
